algoritmo "Verificação Idade"
// Disciplina : LOPAL (Lógica de Programação)

// F9 (Executa meu código)

// Autor: Vitor Veiga
// Data: 07/04/2026

Var

   esgotado : caractere

Inicio
// Entrada de dados

   escreva("O produto está esgotado? (s/n): ")
   leia(esgotado)
   
// Verificação

   se esgotado = "n" entao
   escreva ("Produto disponível para venda.")
   senao
   escreva ("Por favor, reabasteça o estoque.")
      

   fimse
   
FimAlgoritmo
