algoritmo "Verificação Idade"
// Disciplina : LOPAL (Lógica de Programação)

// F9 (Executa meu código)

// Autor: Vitor Veiga
// Data: 07/04/2026

Var

   idade : real

Inicio
// Entrada de dados

   escreva("Digite a idade do visitante: ")
   leia(idade)

// Verificação

      limpatela
      
   se (idade <= 5) ou (idade >= 65) entao
      escreva("A entrada do visitante é gratuita.")
   senao
      escreva("A entrada do visitante é paga.")
   fimSe
   
FimAlgoritmo
